name: PokeEgg
main: br.com.centralandradina.pokeegg.PokeEgg
version: 1.4.0
api-version: 1.20
softdepend:
  - NBTAPI
  - RedProtect
  - WorldGuard

commands:
  pokeegg:
    description: give a PokeEgg to a player
    # usage: 'Usage: /pokeegg give player'
    permission: "pokeegg.give"
    # permission-message: "No permission!"