name: AMFPokeEgg
main: br.com.centralandradina.amfpokeegg.AMFPokeEgg
version: 1.2.0
api-version: 1.20
softdepend:
  - NBTAPI
  - RedProtect

commands:
  pokeegg:
    description: give a PokeEgg to a player
    # usage: 'Usage: /pokeegg give player'
    # permission: "pokeegg.give"
    # permission-message: "No permission!"